"""Generates the model card for one candidate (regenerated for every candidate, checked by gate G8)."""

from __future__ import annotations

import json

from . import explain as E

PROXY_NOTE = (
    "`DrivAge` and `Region` (and, indirectly, `Density`/`Area`) can act as proxies for protected characteristics "
    "(age, and in some jurisdictions ethnicity, religion or socio-economic status). They are kept for realism and "
    "reported by slice; this card does **not** claim the model is fair, compliant, or fit for pricing or underwriting.")


def _fmt(v, nd=5):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else str(v)


def render_card(project, ctx: dict) -> str:
    cand, ev, b, prov = ctx["candidate"], ctx["eval"], ctx["bundle"], ctx["provenance"]
    rdir = ctx["report_dir"]
    syn = b.meta.get("synthetic", False)
    exp = E.get_or_compute(project, cand, b, rdir)
    L: list[str] = []
    a = L.append
    a(f"# Model card: claim frequency `{cand.family}` / candidate `{cand.hash}`\n")
    if syn:
        a("> **Synthetic data.** This candidate was trained on a generated stand-in dataset, not real insurance data. Numbers below describe the stand-in only.\n")
    a("## Intended use\n")
    a("Educational and portfolio demonstration of a *gated model release process* for a motor third-party-liability claim-frequency model "
      "(expected claims per exposure-year). It exists to exercise gates, shadow/canary, drift monitoring and rollback.\n")
    a("## Out-of-scope use\n")
    a("Not for pricing, underwriting, reserving, or any decision about real people. No claim of regulatory compliance, actuarial sign-off or fairness certification. "
      "Severity (claim cost) is not modeled, so nothing here estimates expected loss.\n")
    a("## Data\n")
    rows = b.meta.get("rows", {})
    src = ("freMTPL2freq (French motor TPL), fetched from OpenML data id 41214 at setup, never committed. OpenML lists it as CC0; the original CASdatasets "
           "distribution is GPL, so treat redistribution rights as unsettled (see docs/DATA_CARD.md)." if not syn else "Generated by `examples/claims_frequency/data.py` (labeled synthetic).")
    a(f"- Source: {src}\n- Data version: `{b.data_version}`\n- Rows per split: {rows}\n- Split: {b.meta.get('split')}\n"
      "- **Known gaps: the dataset has no timestamps.** A time-based split is impossible, so *temporal generalization was not evaluated*. "
      "Simulated production traffic replays held-out policies in random order and is **not** real production behavior.\n"
      "- One row per policy; severity data not used; exposure is capped at 1 year, claim counts at 4 (row counts per cleaning rule are in the data-quality report).\n")
    a("## Training procedure\n")
    a(f"- Family: `{cand.family}`; seed `{cand.seed}`; params: `{json.dumps({k: v for k, v in cand.params.items()}, default=str)}`\n"
      "- Target: claim rate (claims per exposure-year), Poisson loss, exposure as sample weight (equivalent to an offset). Tuning used grouped cross-validation inside the training split only; the holdout is evaluated once per candidate.\n"
      "- Optional scale-factor recalibration is fitted on the validation split and is part of the candidate (and its hash).\n")
    a("## Metrics\n")
    a("Evaluated on the holdout, exposure-weighted, 95% bootstrap CIs (policies resampled).\n")
    a("| metric | value | 95% CI |\n|---|---|---|")
    for k, v in ev.metrics.items():
        ci = ev.metric_ci.get(k)
        a(f"| {k} | {_fmt(v)} | {('[' + _fmt(ci[0]) + ', ' + _fmt(ci[1]) + ']') if ci else ''} |")
    a("")
    comp = rdir.parent / "model_comparison.json"
    if comp.exists():
        c = json.loads(comp.read_text())
        a("### Three-model comparison (same holdout)\n")
        a("| model | candidate | deviance | CI | skill vs constant | Gini | CI |\n|---|---|---|---|---|---|---|")
        for r in c["rows"]:
            a(f"| {r['name']} | `{r['hash']}` | {_fmt(r['poisson_deviance'])} | [{_fmt(r['dev_ci'][0])}, {_fmt(r['dev_ci'][1])}] | {_fmt(r['deviance_skill'])} | {_fmt(r['gini'])} | [{_fmt(r['gini_ci'][0])}, {_fmt(r['gini_ci'][1])}] |")
        a("\n" + c["note"] + "\n")
    a("## Slices and calibration\n")
    a("Calibration (exposure-weighted decile error, relative to portfolio frequency): "
      f"**{_fmt(ev.calibration.get('decile_calibration_error'))}**; overall actual/expected: **{_fmt(ev.calibration.get('ae_ratio'))}**.\n")
    a("| slice | level | n | A/E | 95% CI | flag |\n|---|---|---|---|---|---|")
    for sname, rws in ev.slices.items():
        for r in rws:
            ae = r["scores"].get("ae_ratio")
            ci = r["ci"].get("ae_ratio")
            flag = "insufficient data" if r["n"] < r["min_samples"] else ""
            a(f"| {sname} | {r['level']} | {r['n']} | {_fmt(ae, 3) if ae is not None else ''} | {('[' + _fmt(ci[0], 3) + ', ' + _fmt(ci[1], 3) + ']') if ci else ''} | {flag} |")
    a("")
    a("## Explainability\n")
    a(exp["note"] + "\n")
    if exp.get("importance"):
        a("Permutation importance (increase in exposure-weighted deviance when a feature is shuffled):\n")
        a("| feature | deviance increase |\n|---|---|")
        for r in exp["importance"]:
            a(f"| {r['feature']} | {_fmt(r['deviance_increase'], 6)} |")
        a("")
    if exp.get("shap"):
        a(f"{exp['shap']['method']}. Mean |SHAP| by feature:\n")
        a("| feature | mean abs SHAP |\n|---|---|")
        for r in exp["shap"]["mean_abs_shap"]:
            a(f"| {r['feature']} | {_fmt(r['mean_abs'], 4)} |")
        a("")
    if exp.get("glm_coefficients"):
        a("Largest GLM coefficients (rate ratio = exp(coef)):\n\n| term | coef | rate ratio |\n|---|---|---|")
        for r in exp["glm_coefficients"]:
            a(f"| {r['term']} | {_fmt(r['coef_log_rate'], 4)} | {_fmt(r['rate_ratio'], 3)} |")
        a("")
    for f, rws in (exp.get("pdp") or {}).items():
        a(f"Partial dependence, `{f}`: " + ", ".join(f"{r['value']}: {_fmt(r['avg_predicted_rate'], 4)}" for r in rws) + "\n")
    a("## Limitations\n")
    a("- **No timestamps**: temporal generalization, seasonality and trend were not evaluated.\n"
      "- **Simulated traffic and drift**: shadow/canary/drift results come from replaying held-out policies and from synthetic perturbations; they are demonstrations of the machinery, not evidence about real production.\n"
      "- Frequency only; no severity. One country/product/period; extrapolation elsewhere is untested.\n"
      "- Small slices are flagged `insufficient data` and not judged. Bootstrap CIs resample policies and ignore policy-to-policy dependence.\n"
      "- The audit log is a local file: tamper-*evident*, not tamper-*proof*.\n")
    a("### Sensitive features and proxy risk\n")
    a(PROXY_NOTE + "\n")
    a("## Provenance\n")
    a(f"| field | value |\n|---|---|\n| candidate hash | `{cand.hash}` |\n| git SHA | `{prov['git_sha']}` |\n| data version | `{prov['data_version']}` |\n"
      f"| seed | {prov['seed']} |\n| lockfile hash | `{prov['lockfile_hash']}` |\n| gate config hash | `{ctx['gate_config_hash']}` |\n")
    return "\n".join(L)
